version: "3.8"

# This runs the ella demo
# Exactly as it is run in the makefile
# Open localhost:5000 to see the ella demo running

services:

  adminer:
    image: adminer:4.7.7
    restart: always
    networks:
      - app-tier
    ports:
      - 8080:8080

  ella:
    image: dabbleofdevops/ella:1.11.1
    environment:
      ELLA_CONFIG: "/ella/example_config.yml"
      ANNOTATION_SERVICE_URL: "http://ella-anno:6000"
      OFFLINE_MODE: "false"
      DEV_IGV_FASTA: "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/1kg_v37/human_g1k_v37_decoy.fasta"
      DEV_IGV_CYTOBAND: "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/b37/b37_cytoband.txt"
      PTVS_PORT: 5678
      IGV_DATA: "/ella/src/vardb/testdata/igv-data/"
      ATTACHMENT_STORAGE : "/data/attachments/"
      ANALYSES_PATH: "/data/analyses/imported/"
      ANALYSES_INCOMING: "/data/analyses/incoming/"
      PRODUCTION: "false"
      DB_URL: "postgresql:///postgres"
    ports:
      - 5000:5000
    volumes:
      - ./data:/data
      - ./logs:/logs
    networks:
      - app-tier
    command: |
      supervisord -c /ella/ops/dev/supervisor.cfg

  ella-anno:
    image: dabbleofdevops/ella-anno:v2.0.3
    environment:
      DEBUG: "true"
      API_PORT: 6000
    ports:
      - 6000:6000
    depends_on:
      - ella
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge
